#配置其他服务调用的配置文件 端口
#foo 一般用于配置版本
server:
  port: 8070
foo: foo version 1

#配置当前服务注册在eureka server 上的名字
spring:
  application:
    name: configclient

#配置注册中心的访问地址（启动后，当前微服务会找到注册中心进行注册）
#instance.prefer-ip-address 是否将当前服务的ip注册到 eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true